#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Yahoo Fantasy Sports OAuth setup for the live draft-sync script.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=2
ENV_FILE=".yahoo_oauth.env"
REDIRECT_URI="https://localhost:8765/callback"
LEAGUE_URL="https://basketball.fantasysports.yahoo.com/nba/6176"

banner "Yahoo Fantasy Sports API setup"

# ── Stage 1: register a Yahoo developer app ────────────────────────────────
stage "Register a Yahoo developer app"
say "This creates a free, personal-use app so a local script can read your"
say "league's draft picks. Only you can do this part — it's your Yahoo account."
open_url "https://developer.yahoo.com/apps/create/"
step "Application Name: anything you like, e.g. \"DURANT Draft Sync\"."
step "Application Type / Homepage URL: choose \"Web Application\" if asked;"
note "  any Homepage URL works (e.g. https://github.com) — it's not used."
step "Redirect URI(s): enter exactly: ${REDIRECT_URI}"
note "  (must be this exact value — the sync script listens on this port)"
step "API Permissions: check \"Fantasy Sports\" and set it to Read (not Read/Write)."
note "Yahoo's developer console UI shifts around occasionally — if a label above"
note "doesn't match exactly, look for the nearest equivalent (redirect URI field,"
note "an API-permissions/scopes section, Fantasy Sports read access)."
step "Create the app, then open its details page to reveal the Client ID and"
step "Client Secret."
ask CLIENT_ID "Paste the Client ID (Consumer Key):"
ask_secret CLIENT_SECRET "Paste the Client Secret (Consumer Secret):"
write_env CLIENT_ID "$CLIENT_ID"
write_env CLIENT_SECRET "$CLIENT_SECRET"
write_env REDIRECT_URI "$REDIRECT_URI"
write_env LEAGUE_URL "$LEAGUE_URL"

# ── Stage 2: one-time login + consent, exchanged for tokens ────────────────
stage "Authorize access to your league"
say "Now a one-time Yahoo login: you approve read access to your fantasy data,"
say "and this script catches the redirect locally to finish the handshake."
say "(Nothing is sent anywhere except Yahoo's own servers.)"

CODE_FILE=$(mktemp)
PORT=8765
CERT_DIR=$(mktemp -d)

say "Yahoo now requires an https redirect URI even for localhost, so this"
say "generates a throwaway, self-signed cert just for catching the redirect."
openssl req -x509 -newkey rsa:2048 -keyout "${CERT_DIR}/key.pem" -out "${CERT_DIR}/cert.pem" \
  -days 1 -nodes -subj "/CN=localhost" -addext "subjectAltName=DNS:localhost" >/dev/null 2>&1

LISTENER_LOG=$(mktemp)
say "Starting a temporary local listener on port ${PORT} for the redirect..."
python3 - "$PORT" "$CODE_FILE" "${CERT_DIR}/cert.pem" "${CERT_DIR}/key.pem" <<'PYEOF' >"$LISTENER_LOG" 2>&1 &
import sys, ssl, time, http.server, urllib.parse

port = int(sys.argv[1])
code_file = sys.argv[2]
certfile, keyfile = sys.argv[3], sys.argv[4]
deadline = time.time() + 900  # 15 minutes -- plenty for a slow login/2FA

found = {"code": None}

class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        qs = urllib.parse.parse_qs(urllib.parse.urlparse(self.path).query)
        code = qs.get("code", [""])[0]
        self.send_response(200)
        self.send_header("Content-Type", "text/html")
        self.end_headers()
        if code:
            found["code"] = code
            self.wfile.write(
                b"<html><body><h3>Authorized. You can close this tab and "
                b"return to the terminal.</h3></body></html>"
            )
        else:
            # e.g. a browser's automatic /favicon.ico request -- ignore it
            # and keep waiting rather than treating it as "the" request.
            self.wfile.write(b"")
    def log_message(self, *args):
        pass

httpd = http.server.HTTPServer(("127.0.0.1", port), Handler)
ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)
httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)
print("listening", flush=True)

while found["code"] is None and time.time() < deadline:
    httpd.timeout = 5
    httpd.handle_request()

if found["code"]:
    with open(code_file, "w") as f:
        f.write(found["code"])
PYEOF
LISTENER_PID=$!

# Confirm the listener actually came up before sending the user into Yahoo's
# login flow -- turns a silent hang into an immediate, visible failure.
LISTENER_UP=0
for _ in $(seq 1 20); do
  if grep -q "listening" "$LISTENER_LOG" 2>/dev/null; then LISTENER_UP=1; break; fi
  kill -0 "$LISTENER_PID" 2>/dev/null || break
  sleep 0.25
done
if [[ "$LISTENER_UP" != "1" ]]; then
  warn "The local listener didn't start. Here's what it said:"
  cat "$LISTENER_LOG"
  rm -f "$CODE_FILE" "$LISTENER_LOG"; rm -rf "$CERT_DIR"
  exit 1
fi

AUTH_URL="https://api.login.yahoo.com/oauth2/request_auth?client_id=${CLIENT_ID}&redirect_uri=${REDIRECT_URI}&response_type=code&scope=fspt-r&language=en-us"
open_url "$AUTH_URL"
step "Log into Yahoo if prompted, then click Agree/Allow to grant read access."
warn "The redirect lands on the self-signed localhost cert above, so your"
warn "browser will show a \"connection is not private\" warning. That's"
warn "expected — click Advanced → Proceed to localhost (it's your own machine)."
say "Waiting for the redirect (up to 15 minutes)..."

for _ in $(seq 1 900); do
  [[ -s "$CODE_FILE" ]] && break
  kill -0 "$LISTENER_PID" 2>/dev/null || break
  sleep 1
done
kill "$LISTENER_PID" >/dev/null 2>&1 || true
AUTH_CODE=$(cat "$CODE_FILE" 2>/dev/null || true)
if [[ -z "$AUTH_CODE" ]]; then
  warn "No authorization code arrived. Listener output, for diagnosis:"
  cat "$LISTENER_LOG"
fi
rm -f "$CODE_FILE" "$LISTENER_LOG"
rm -rf "$CERT_DIR"

if [[ -z "$AUTH_CODE" ]]; then
  warn "Didn't catch the redirect automatically."
  note "If the browser landed on a localhost page with ?code=... in its address"
  note "bar, paste just that code value below."
  ask AUTH_CODE "Paste the authorization code:"
fi

step "Exchanging the authorization code for an access token..."
TOKEN_JSON=$(curl -s -u "${CLIENT_ID}:${CLIENT_SECRET}" \
  --data-urlencode "grant_type=authorization_code" \
  --data-urlencode "redirect_uri=${REDIRECT_URI}" \
  --data-urlencode "code=${AUTH_CODE}" \
  "https://api.login.yahoo.com/oauth2/get_token")

ACCESS_TOKEN=$(python3 -c "import json,sys; print(json.loads(sys.argv[1]).get('access_token',''))" "$TOKEN_JSON" 2>/dev/null || true)
REFRESH_TOKEN=$(python3 -c "import json,sys; print(json.loads(sys.argv[1]).get('refresh_token',''))" "$TOKEN_JSON" 2>/dev/null || true)

if [[ -z "$ACCESS_TOKEN" || -z "$REFRESH_TOKEN" ]]; then
  warn "Token exchange didn't return what was expected. Yahoo's response:"
  say "$TOKEN_JSON"
  warn "Nothing was written for the access/refresh token — re-run this script"
  warn "once the app's redirect URI and permissions are confirmed correct."
else
  write_env YAHOO_ACCESS_TOKEN "$ACCESS_TOKEN"
  write_env YAHOO_REFRESH_TOKEN "$REFRESH_TOKEN"
  write_env YAHOO_TOKEN_ISSUED_AT "$(date +%s)"
  say "Got it — access + refresh tokens saved."
  note "scripts/live_draft_sync.py refreshes the access token itself once it"
  note "expires (Yahoo access tokens are short-lived; the refresh token is not)."
fi

finish
say "All Yahoo credentials live in .yahoo_oauth.env (already git-ignored)."
say "Next: run scripts/live_draft_sync.py during your draft."
